country: china
province: bejing
city: bejing
area: henan

port: 8080

party: true

birthday: 2000-03-06

user:
  name1: zs
  age: 16

a:
  b:
    c:
      d:
        e: 123

likes:
  - game
  - music
  - sleep

likes2: [game,music,sleep]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 18

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 18
users3: [{name:zhangsan,age:18},{name:lisi,age:19}]
server:
  port: 80

baseDir: c:\windows

#使用${属性名}引用数据

tempDir: ${baseDir}\temp

#使用引号包裹的字符串中 ，其中转义字符可以生效
tempDir2: "${baseDir}\temp \t1 \t2 "

#创建类，用于封装下面数据
# 由spring帮我们去加载数据到对象模块中，一定要告诉spring加载以下数据
#使用时候从spring中直接获取数据

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:myql://localhost/springboot_db
  username: root
  password: root




